db.disneys.insertMany([
   { name: "Mickey Mouse" },
   { name: "Timon and Pumbaa" },
   { name: "Minnie Mouse" },
   { name: "Sebastian" },
   { name: "Donald Duck" },
   { name: "Lumiere" },
   { name: "Goofy" },
   { name: "Cogsworth" },
   { name: "Woody" },
   { name: "Genie" },
   { name: "Mushu" },
   { name: "Nemo" },
   { name: "Jiminy Cricket" },
   { name: "Dory" },
   { name: "Jaq and Gus" },
   { name: "Simba" },
   { name: "Olaf" },
   { name: "Belle" },
   { name: "Sven" },
   { name: "Ariel" },
   { name: "Kristoff" },
   { name: "Cinderella" },
   { name: "Hiro Hamada" },
   { name: "Elsa" },
   { name: "Baymax" },
   { name: "Anna" },
   { name: "Mater" },
   { name: "Rapunzel" },
   { name: "Lightning McQueen" },
   { name: "Peter Pan" },
   { name: "WALL-E" },
   { name: "Tinker Bell" },
   { name: "Eve" },
   { name: "Winnie the Pooh" },
   { name: "Merida" },
   { name: "Tiana" },
   { name: "Lilo" },
   { name: "Aladdin" },
   { name: "Jumba Jookiba" },
   { name: "Pocahontas" },
   { name: "Maui" },
   { name: "Mulan" },
   { name: "Heihei" },
   { name: "Hercules" },
   { name: "Pinocchio" },
   { name: "Stitch" },
   { name: "Moana" },
   { name: "Black Widow" },
   { name: "Iron Man" },
   { name: "Captain America" },
   { name: "Spider-Man" },
   { name: "Shuri" },
   { name: "Bucky Barnes" },
   { name: "Peggy Carter" },
   { name: "Hawkeye" },
   { name: "Ant-Man" },
   { name: "The Wasp" },
   { name: "Yondu" },
   { name: "Ursula" },
   { name: "Jafar" },
   { name: "Scar" },
   { name: "Flounder" },
   { name: "Remy" },
   { name: "Disgust" }
]);

db.actors.insertMany([
   {name: "Jean Reno"},
   {name: "Tom Hanks"},
   {name: "Anthony Hopkins"},
   {name: "Marion Cotillard"},
   {name: "Meryl Streep"},
   {name: "Daniel Craig"},
   {name: "Vincent Cassel"},
   {name: "Brad Pitt"},
   {name: "Kate Winslet"},
   {name: "Audrey Tautou"},
   {name: "Leonardo DiCaprio"},
   {name: "Benedict Cumberbatch"},
   {name: "Gérard Depardieu"},
   {name: "Jennifer Lawrence"},
   {name: "Helen Mirren"},
   {name: "Sophie Marceau"},
   {name: "Denzel Washington"},
   {name: "Colin Firth"},
   {name: "Omar Sy"},
   {name: "Robert De Niro"},
   {name: "Emma Watson"},
   {name: "Juliette Binoche"},
   {name: "Al Pacino"},
   {name: "Jude Law"},
   {name: "Isabelle Huppert"},
   {name: "Angelina Jolie"},
   {name: "Tom Hardy"},
   {name: "Jean Dujardin"},
   {name: "George Clooney"},
   {name: "Keira Knightley"},
   {name: "Léa Seydoux"},
   {name: "Sandra Bullock"},
   {name: "Idris Elba"},
   {name: "François Cluzet"},
   {name: "Johnny Depp"},
   {name: "Michael Caine"},
   {name: "Catherine Deneuve"},
   {name: "Julia Roberts"},
   {name: "Maggie Smith"},
   {name: "Romain Duris"},
   {name: "Scarlett Johansson"},
   {name: "Emily Blunt"},
   {name: "Nathalie Baye"},
   {name: "Will Smith"},
   {name: "Hugh Grant"},
   {name: "Vincent Lindon"},
   {name: "Emma Stone"},
   {name: "Emma Thompson"},
   {name: "Emmanuelle Béart"},
   {name: "Ryan Gosling"},
   {name: "Sean Connery"},
   {name: "Alain Delon"},
   {name: "Christian Bale"},
   {name: "Ian McKellen"},
   {name: "Bérénice Bejo"},
   {name: "Tom Cruise"},
   {name: "Judi Dench"},
   {name: "Louis de Funès"},
   {name: "Clint Eastwood"},
   {name: "David Tennant"},
   {name: "Omar Sharif"},
   {name: "Mark Wahlberg"},
   {name: "Carey Mulligan"},
   {name: "Mathieu Kassovitz"},
   {name: "Harrison Ford"},
   {name: "Timothy Spall"},
   {name: "Daniel Auteuil"},
   {name: "Morgan Freeman"},
   {name: "Ralph Fiennes"},
   {name: "Guillaume Canet"},
   {name: "Samuel L. Jackson"},
   {name: "Eddie Redmayne"},
   {name: "Viola Davis"},
    {name: "Tom Hiddleston"},
    {name: "Carey Mulligan" },
   { name: "Mathieu Kassovitz" },
   { name: "Harrison Ford" },
   { name: "Timothy Spall" },
   { name: "Daniel Auteuil" },
   { name: "Morgan Freeman" },
   { name: "Ralph Fiennes" },
   { name: "Guillaume Canet" },
   { name: "Samuel L. Jackson" },
   { name: "Eddie Redmayne" },
   { name: "Viola Davis" },
   { name: "Tom Hiddleston" },
   { name: "Matthew McConaughey" },
   { name: "Benedict Wong" },
   { name: "Anne Hathaway" },
   { name: "Andrew Scott" },
   { name: "Daniel Day-Lewis" },
   { name: "Chiwetel Ejiofor" },
   { name: "Cate Blanchett" },
   { name: "John Boyega" },
   { name: "Heath Ledger" },
   { name: "Helena Bonham Carter" },
   { name: "Robert Downey Jr." },
   { name: "Tilda Swinton" },
   { name: "Robin Williams" },
   { name: "Naomi Watts" },
   { name: "Dustin Hoffman" },
   { name: "Iain Glen" },
   { name: "Keanu Reeves" },
   { name: "Colin Farrell" },
   { name: "Timothée Chalamet" },
   { name: "Emily Mortimer" },
   { name: "Lupita Nyong'o" },
   { name: "Dev Patel" }
]);

db.singers.insertMany([
   { name: "Edith Piaf" },
   { name: "The Beatles" },
   { name: "Jacques Brel" },
   { name: "Michael Jackson" },
   { name: "Serge Gainsbourg" },
   { name: "Madonna" },
   { name: "Charles Aznavour" },
   { name: "Whitney Houston" },
   { name: "Johnny Hallyday" },
   { name: "Prince" },
   { name: "Dalida" },
   { name: "Elton John" },
   { name: "Francis Cabrel" },
   { name: "Freddie Mercury/Queen" },
   { name: "Jean-Jacques Goldman" },
   { name: "David Bowie" },
   { name: "Mylène Farmer" },
   { name: "Stevie Wonder" },
   { name: "Vanessa Paradis" },
   { name: "Bruce Springsteen" },
   { name: "Zazie" },
   { name: "Bob Dylan" },
   { name: "Alain Bashung" },
   { name: "Fleetwood Mac" },
   { name: "Patricia Kaas" },
   { name: "The Rolling Stones" },
   { name: "Carla Bruni" },
   { name: "Pink Floyd" },
   { name: "Mireille Mathieu" },
   { name: "Led Zeppelin" },
   { name: "Renaud" },
   { name: "Nirvana" },
   { name: "Christophe Maé" },
   { name: "Pearl Jam" },
   { name: "Patrick Bruel" },
   { name: "U2" },
   { name: "Kyo" },
   { name: "Metallica" },
   { name: "Indochine" },
   { name: "Guns N' Roses" },
   { name: "Téléphone" },
   { name: "AC/DC" },
   { name: "Noir Désir" },
   { name: "Aerosmith" },
   { name: "Superbus" },
   { name: "Bon Jovi" },
   { name: "Céline Dion" },
   { name: "Madonna" },
   { name: "Stromae" },
   { name: "Mariah Carey" },
   { name: "Johnny Clegg" },
   { name: "Beyoncé" },
   { name: "Angèle" },
   { name: "Lady Gaga" },
   { name: "La Grande Sophie" },
   { name: "Taylor Swift" },
   { name: "Christophe Willem" },
   { name: "Rihanna" },
   { name: "Calogero" },
   { name: "Adele" },
   { name: "Véronique Sanson" },
   { name: "Justin Timberlake" },
   { name: "Michel Sardou" },
   { name: "Bruno Mars" },
   { name: "Benjamin Biolay" },
   { name: "Ed Sheeran" },
   { name: "Julien Doré" },
   { name: "Justin Bieber" },
   { name: "Francis Lalanne" },
   { name: "The Red Hot Chili Peppers" },
   { name: "Nolwenn Leroy" },
   { name: "Oasis" }
]);

db.jobs.insertMany([
   { name: "Comptable" },
   { name: "Acupuncteur" },
   { name: "Architecte" },
   { name: "Détective privé" },
   { name: "Artiste" },
   { name: "Designer de jeux vidéo" },
   { name: "Boulanger" },
   { name: "Critique de cinéma" },
   { name: "Banquier" },
   { name: "Chercheur de fantômes" },
   { name: "Barman" },
   { name: "Expert en éthique de l'IA" },
   { name: "Conducteur de bus" },
   { name: "Parolier" },
   { name: "Chef cuisinier" },
   { name: "Testeur de nourriture pour animaux de compagnie" },
   { name: "Ingénieur civil" },
   { name: "Biographe" },
   { name: "Agent de nettoyage" },
   { name: "Spécialiste en communication non verbale" },
   { name: "Programmeur informatique" },
   { name: "Évaluateur de bijoux" },
   { name: "Représentant du service client" },
   { name: "Astrologue" },
   { name: "Dentiste" },
   { name: "Dresseur de chiens" },
   { name: "Docteur" },
   { name: "Thérapeute en art" },
   { name: "Électricien" },
   { name: "Géomètre" },
   { name: "Ingénieur" },
   { name: "Créateur de mode pour animaux de compagnie" },
   { name: "Agriculteur" },
   { name: "Spécialiste en énergie renouvelable" },
   { name: "Styliste" },
   { name: "Éducateur canin" },
   { name: "Pompier" },
   { name: "Expert en éclairage de scène" },
   { name: "Entraîneur de fitness" },
   { name: "Contrôleur de la qualité de l'air" },
   { name: "Agent de bord" },
   { name: "Art-thérapeute" },
   { name: "Coiffeur" },
   { name: "Éthologue" },
   { name: "Gérant d'hôtel" },
   { name: "Conservateur de musée" },
   { name: "Responsable des ressources humaines" },
   { name: "Parfumeur" },
   { name: "Journaliste" },
   { name: "Ethnographe" },
   { name: "Avocat" },
   { name: "Chirurgien esthétique" },
   { name: "Bibliothécaire" },
   { name: "Analyste du comportement" },
   { name: "Enseignant" },
   { name: "Analyste de la criminalité" },
   { name: "Chercheur en cryptographie" },
   { name: "Technicien en maintenance" },
   { name: "Historien de l'art" },
   { name: "Directeur marketing" },
   { name: "Massothérapeute" },
   { name: "Ingénieur mécanique" },
   { name: "Optométriste	" },
   { name: "Plombier" },
   { name: "Psychologue	" },
   { name: "Agent immobilier" },
   { name: "Mécanicien automobile" },
   { name: "Enseignant d'école primaire	" },
   { name: "Enseignant d'université" },
   { name: "Écrivain" }
]);

db.movies.insertMany([
   { name: "Bienvenue chez les Ch'tis" },
   { name: "Intouchables" },
   { name: "Les Visiteurs" },
   { name: "La French" },
   { name: "Les Tuches" },
   { name: "Qu'est-ce qu'on a fait au Bon Dieu ?" },
   { name: "Les Bronzés" },
   { name: "La Grande Vadrouille" },
   { name: "Astérix et Obélix Mission Cléopatre" },
   { name: "La Vérité si je mens !" },
   { name: "Les Bronzés font du ski" },
   { name: "RRRrrrr!!!" },
   { name: "L'Arnacœur" },
   { name: "Taxi" },
   { name: "OSS 117" },
   { name: "Le Prénom" },
   { name: "Le Dîner de Cons" },
   { name: "Les Infidèles" },
   { name: "Les Choristes" },
   { name: "Le Petit Nicolas" },
   { name: "Le Fabuleux Destin d'Amélie Poulain" },
   { name: "Le Pacte des loups" },
   { name: "Le Père Noël est une ordure" },
   { name: "Les Rivières pourpres" },
   { name: "Camping" },
   { name: "Nikita" },
   { name: "Un Indien dans la ville" },
   { name: "Pattaya" },
   { name: "La Cage aux Folles" },
   { name: "Avatar" },
   { name: "Titanic" },
   { name: "Star Wars" },
   { name: "Jurassic World" },
   { name: "Frozen" },
   { name: "Harry Potter et les Reliques de la Mort" },
   { name: "The Dark Knight : Le Chevalier noir" },
   { name: "Fast and Furious" },
   { name: "Le Hobbit" },
   { name: "Iron Man" },
   { name: "Le Seigneur des Anneaux" },
   { name: "Jumanji" },
   { name: "Les Minions" },
   { name: "Finding Dory" },
   { name: "Spectre" },
   { name: "Skyfall" },
   { name: "Pirates des Caraïbes" },
   { name: "Le Retour de Mary Poppins" },
   { name: "La Belle et la Bête" },
   { name: "La Reine des neiges" },
   { name: "Transformers" },
   { name: "Les Animaux fantastiques" },
   { name: "Transformers : La Revanche" },
   { name: "Mission: Impossible" },
   { name: "Les Avengers" },
   { name: "Spider-Man" },
   { name: "Forrest Gump" },
   { name: "Le Silence des Agneaux" },
   { name: "Birdman" },
   { name: "Million Dollar Baby" },
   { name: "Rocky" },
   { name: "Le parrain" },
   { name: "Gladiator" },
   { name: "Le Discours d'un Roi" },
   { name: "Rain Man" },
   { name: "Argo" },
   { name: "Le Patient Anglais" },
   { name: "American Beauty" },
   { name: "Braveheart" },
   { name: "La Liste de Schindler" },
   { name: "Les Évadés" },
   { name: "No Country for Old Men" },
   { name: "Grease" },
   { name: "Pretty Woman" },
   { name: "Le diable s'habille en Prada" },
   { name: "Black Panther" },
   { name: "Joker" },
   { name: "La ligne verte" },
   { name: "12 hommes en colère" },
   { name: "Vol au dessus d'un nid de coucou" }
]);


db.athletes.insertMany([
   { name: "Muhammad Ali" },
   { name: "Michael Jordan" },
   { name: "Pelé" },
   { name: "Usain Bolt" },
   { name: "Lionel Messi" },
   { name: "Cristiano Ronaldo" },
   { name: "Diego Maradona" },
   { name: "Roger Federer" },
   { name: "Serena Williams" },
   { name: "Rafael Nadal" },
   { name: "Tiger Woods" },
   { name: "Mike Tyson" },
   { name: "Floyd Mayweather Jr." },
   { name: "Kobe Bryant" },
   { name: "Michael Phelps" },
   { name: "Carl Lewis" },
   { name: "Jesse Owens" },
   { name: "Wayne Gretzky" },
   { name: "David Beckham" },
   { name: "Zinedine Zidane" },
   { name: "Ronaldinho" },
   { name: "Neymar" },
   { name: "Lebron James" },
   { name: "Shaquille O'Neal" },
   { name: "Magic Johnson" },
   { name: "Larry Bird" },
   { name: "Manny Pacquiao" },
   { name: "Sugar Ray Leonard" },
   { name: "Georges St-Pierre" },
   { name: "Royce Gracie" },
   { name: "Jon Jones" },
   { name: "Conor McGregor" },
   { name: "Georges Laraque" },
   { name: "Michael Schumacher" },
   { name: "Ayrton Senna" },
   { name: "Lewis Hamilton" },
   { name: "Valentino Rossi" },
   { name: "Eddy Merckx" },
   { name: "Lance Armstrong" },
   { name: "Martina Navratilova" },
   { name: "Steffi Graf" },
   { name: "Novak Djokovic" },
   { name: "Pete Sampras" },
   { name: "Andre Agassi" },
   { name: "Roger Clemens" },
   { name: "Barry Bonds" },
   { name: "Michael Vick" },
   { name: "Jerry Rice" },
   { name: "Tom Brady" },
   { name: "Joe Montana" },
   { name: "Serena Williams" },
   { name: "Martina Hingis" },
   { name: "Ronda Rousey" },
   { name: "Holly Holm" },
   { name: "Simone Biles" },
   { name: "Nadia Comaneci" },
   { name: "Bonnie Blair" },
   { name: "Eric Heiden" },
   { name: "Wayne Gretzky" },
   { name: "Bobby Orr" },
   { name: "Mario Lemieux" },
   { name: "Sidney Crosby" },
   { name: "Michael Owen" },
   { name: "Johan Cruyff" },
   { name: "Franz Beckenbauer" },
   { name: "Lev Yashin" },
   { name: "Zlatan Ibrahimovic" },
   { name: "Usain Bolt" },
   { name: "Carl Lewis" },
   { name: "Edwin Moses" },
   { name: "Jackie Joyner-Kersee" },
   { name: "Greg Louganis" },
   { name: "Teddy Riner" },
   { name: "Marcel Cerdan" },
   { name: "Khabib Nurmagomedov" },
   { name: "Francis N'Gannou" },
   { name: "Kyrie Irving" },
   { name: "Vince Carter " }
]);


db.sports.insertMany([
   { name: "Athlétisme" },
   { name: "Aviron" },
   { name: "Badminton" },
   { name: "Baseball" },
   { name: "Basket-ball" },
   { name: "Beach-volley" },
   { name: "Billard" },
   { name: "Biathlon" },
   { name: "Boxe" },
   { name: "Canoë-kayak" },
   { name: "Cricket" },
   { name: "Curling" },
   { name: "Cyclisme" },
   { name: "Danse sportive" },
   { name: "Équitation" },
   { name: "Escalade" },
   { name: "Escrime" },
   { name: "Football" },
   { name: "Football américain" },
   { name: "Golf" },
   { name: "Gymnastique artistique" },
   { name: "Gymnastique rythmique" },
   { name: "Haltérophilie" },
   { name: "Handball" },
   { name: "Hockey sur gazon" },
   { name: "Hockey sur glace" },
   { name: "Judo" },
   { name: "Karaté" },
   { name: "Kitesurf" },
   { name: "Luge" },
   { name: "Motocross" },
   { name: "Natation" },
   { name: "Patinage artistique" },
   { name: "Patinage de vitesse" },
   { name: "Pêche sportive" },
   { name: "Pentathlon moderne" },
   { name: "Pétanque" },
   { name: "Planche à voile" },
   { name: "Plongée sous-marine" },
   { name: "Rafting" },
   { name: "Randonnée pédestre" },
   { name: "Roller derby" },
   { name: "Rugby" },
   { name: "Ski alpin" },
   { name: "Ski de fond" },
   { name: "Snowboard" },
   { name: "Squash" },
   { name: "Surf" },
   { name: "Taekwondo" },
   { name: "Tennis" },
   { name: "Tennis de table" },
   { name: "Tir à l'arc" },
   { name: "Tir sportif" },
   { name: "Triathlon" },
   { name: "Ultimate Frisbee" },
   { name: "Varappe" },
   { name: "Voile" },
   { name: "Volley-ball" },
   { name: "Water-polo" },
   { name: "Yoga" },
   { name: "Marche nordique" },
   { name: "Course d'orientation" },
   { name: "Course de chevaux" },
   { name: "Polo" },
   { name: "Course de dragsters" },
   { name: "Course automobile" },
   { name: "Course de drones" },
   { name: "Course de motos" },
   { name: "Course de bateaux" },
   {name: "Aérobic"},
  {name: "Alpinisme"},
  {name: "Barre au sol"},
  {name: "Cross-country"},
  {name: "Danse contemporaine"},
  {name: "Hapkido"},
  {name: "Jiu-jitsu"},
  {name: "Karaté Kyokushinkai"},
  {name: "Kung-fu"},
  {name: "Taï-chi-chuan"}
]);

db.animals.insertMany([
   { name: "Lion" },
   { name: "Tigre" },
   { name: "Éléphant" },
   { name: "Girafe" },
   { name: "Zèbre" },
   { name: "Ours polaire" },
   { name: "Panda" },
   { name: "Léopard" },
   { name: "Guépard" },
   { name: "Jaguar" },
   { name: "Loup" },
   { name: "Renard" },
   { name: "Coyote" },
   { name: "Hyène" },
   { name: "Chat" },
   { name: "Chien" },
   { name: "Lapin" },
   { name: "Koala" },
   { name: "Kangourou" },
   { name: "Wombat" },
   { name: "Ours brun" },
   { name: "Grizzly" },
   { name: "Puma" },
   { name: "Lynx" },
   { name: "Caribou" },
   { name: "Cerf" },
   { name: "Antilope" },
   { name: "Chameau" },
   { name: "Dromadaire" },
   { name: "Gorille" },
   { name: "Chimpanzé" },
   { name: "Orang-outan" },
   { name: "Babouin" },
   { name: "Singe araignée" },
   { name: "Mandrill" },
   { name: "Perroquet" },
   { name: "Toucan" },
   { name: "Colibri" },
   { name: "Flamant rose" },
   { name: "Pingouin" },
   { name: "Baleine" },
   { name: "Dauphin" },
   { name: "Requin" },
   { name: "Poulpe" },
   { name: "Calmar géant" },
   { name: "Crocodile" },
   { name: "Alligator" },
   { name: "Serpent" },
   { name: "Cobra" },
   { name: "Python" },
   { name: "Scorpion" },
   { name: "Araignée" },
   { name: "Fourmi" },
   { name: "Abeille" },
   { name: "Papillon" },
   { name: "Libellule" },
   { name: "Escargot" },
   { name: "Crabe" },
   { name: "Étoile de mer" },
   { name: "Méduse" },
   { name: "Crapaud" },
   { name: "Grenouille" },
   { name: "Salamandre" },
   { name: "Iguane" },
   { name: "Gecko" },
   { name: "Caméléon" },
   { name: "Tortue" },
   { name: "Crevette" },
   { name: "Homard" },
   { name: "Écrevisse" },
   { name: "Pieuvre" },
   { name: "Coquille Saint-Jacques" },
   { name: "Mouette" },
   { name: "Corbeau" },
   { name: "Aigle" },
   { name: "Faucon" },
   { name: "Hibou" },
   { name: "Colombe" },
   { name: "Pigeon" },
   { name: "Rhinocéros" }
]);

db.histories.insertMany([
  { name: "Jésus-Christ" },
  { name: "Bouddha" },
  { name: "Alexandre le Grand" },
  { name: "Jules César" },
  { name: "Cléopâtre" },
  { name: "Napoléon Bonaparte" },
  { name: "Genghis Khan" },
  { name: "George Washington" },
  { name: "Abraham Lincoln" },
  { name: "Albert Einstein" },
  { name: "Martin Luther King Jr." },
  { name: "Mahatma Gandhi" },
  { name: "Winston Churchill" },
  { name: "Franklin D. Roosevelt" },
  { name: "John F. Kennedy" },
  { name: "Nelson Mandela" },
  { name: "Galilée" },
  { name: "Isaac Newton" },
  { name: "Charles Darwin" },
  { name: "Marie Curie" },
  { name: "Michel-Ange" },
  { name: "Léonard de Vinci" },
  { name: "Vincent van Gogh" },
  { name: "Pablo Picasso" },
  { name: "William Shakespeare" },
  { name: "Edgar Allan Poe" },
  { name: "Johann Sebastian Bach" },
  { name: "Wolfgang Amadeus Mozart" },
  { name: "Ludwig van Beethoven" },
  { name: "Frédéric Chopin" },
  { name: "Charles Babbage" },
  { name: "Thomas Edison" },
  { name: "Alexander Graham Bell" },
  { name: "Henry Ford" },
  { name: "Steve Jobs" },
  { name: "Mark Zuckerberg" },
  { name: "Mahomet" },
  { name: "Confucius" },
  { name: "Socrate" },
  { name: "Aristote" },
  { name: "La Guerre de Troie" },
  { name: "La Révolution française" },
  { name: "La chute de l'Empire romain" },
  { name: "La découverte de l'Amérique" },
  { name: "La Première Guerre mondiale" },
  { name: "La découverte de l'électricité" },
  { name: "Discours de Martin Luther King Jr. (\"I Have a Dream\", 1963)" },
  { name: "La construction de la Grande Muraille de Chine" },
  { name: "La Renaissance" },
  { name: "La Guerre froide" },
  { name: "La découverte de la gravitation universelle" },
  { name: "La Révolution industrielle" },
  { name: "La Guerre des étoiles" },
  { name: "La chute du mur de Berlin" },
  { name: "La découverte de l'ADN" },
  { name: "La Guerre des Six Jours" },
  { name: "La construction de la Tour Eiffel" },
  { name: "La Guerre de Cent Ans" },
  { name: "L'assassinat de Jules César" },
  { name: "La conquête de l'Espagne par les Arabes" },
  { name: "La découverte de l'Amérique du Sud" }
]);

db.brands.insertMany([
   { name: "Air France" },
   { name: "Peugeot" },
   { name: "Renault" },
   { name: "Michelin" },
   { name: "Carrefour" },
   { name: "Total" },
   { name: "Danone" },
   { name: "L'Oréal" },
   { name: "Chanel" },
   { name: "Hermès" },
   { name: "Louis Vuitton" },
   { name: "Cartier" },
   { name: "Yves Saint Laurent" },
   { name: "Dior" },
   { name: "Givenchy" },
   { name: "Guerlain" },
   { name: "Clarins" },
   { name: "Airbus" },
   { name: "Orange" },
   { name: "Bouygues Telecom" },
   { name: "SFR" },
   { name: "Free" },
   { name: "EDF" },
   { name: "Engie" },
   { name: "Veolia" },
   { name: "Suez" },
   { name: "Vinci" },
   { name: "Sanofi" },
   { name: "LVMH" },
   { name: "AccorHotels" },
   { name: "Club Med" },
   { name: "RATP" },
   { name: "SNCF" },
   { name: "Air Liquide" },
   { name: "Safran" },
    { name: "Thales" },
   { name: "Alstom" },
   { name: "Schneider Electric" },
   { name: "Siemens" },
   { name: "Orange" },
   { name: "Canal+" },
   { name: "Le Figaro" },
   { name: "Le Monde" },
   { name: "Les Echos" },
   { name: "BNP Paribas" },
   { name: "Société Générale" },
   { name: "Crédit Agricole" },
   { name: "La Poste" },
   { name: "La Redoute" },
   { name: "Fnac" },
   { name: "Decathlon" },
   { name: "Leroy Merlin" },
   { name: "Castorama" },
   { name: "Ikea" },
   { name: "Carrefour" },
   { name: "Auchan" },
   { name: "Intermarché" },
   { name: "Monoprix" },
   { name: "Leclerc" },
   { name: "Peugeot" },
   { name: "Renault" },
   { name: "Michelin" },
   { name: "Citroën" },
   { name: "Airbus" },
   { name: "Air France" },
   { name: "SNCF" },
   { name: "Apple" },
   { name: "Nike" },
   { name: "Coca-Cola" },
   { name: "Google" },
   { name: "McDonald's" },
   { name: "Amazon" },
   { name: "Samsung" },
   { name: "Toyota" },
   { name: "BMW" },
   { name: "Mercedes-Benz" },
   { name: "Audi" },
   { name: "Ford" },
   { name: "Chevrolet" },
   { name: "Pepsi" },
   { name: "Adidas" },
   { name: "Microsoft" },
   { name: "Procter & Gamble" },
   { name: "Unilever" },
   { name: "Nestlé" }
]);

db.expressions.insertMany([
   { name: "Avoir un chat dans la gorge" },
   { name: "Avoir les yeux plus gros que le ventre" },
   { name: "Avoir un coup de foudre" },
   { name: "À bon entendeur salut" },
   { name: "Appuyer sur le champignon" },
   { name: "Avoir la tête dans les nuages" },
   { name: "Avoir le cœur sur la main" },
   { name: "Avoir un cœur d'artichaut" },
   { name: "C'est du gâteau" },
   { name: "C'est la fin des haricots" },
   { name: "C'est la goutte d'eau qui fait déborder le vase" },
   { name: "C'est la vie" },
   { name: "Chercher une aiguille dans une botte de foin" },
   { name: "Coûter les yeux de la tête" },
   { name: "De fil en aiguille" },
   { name: "Donner sa langue au chat" },
   { name: "Être à l'ouest" },
   { name: "Être dans les nuages" },
   { name: "Être dans la lune" },
   { name: "Être aux abonnés absents" },
   { name: "Faire des pieds et des mains" },
   { name: "Faire la tête" },
   { name: "Faire sa valise" },
   { name: "Il ne faut pas mettre tous ses œufs dans le même panier" },
   { name: "Être sur un petit nuage" },
   { name: "Jouer avec le feu" },
   { name: "Lâcher la grappe" },
   { name: "Manger sur le pouce" },
   { name: "Mettre de l'eau dans son vin" },
   { name: "Mettre les pieds dans le plat" },
   { name: "Mettre la main à la pâte" },
   { name: "Ne pas avoir sa langue dans sa poche" },
   { name: "Ne pas y aller par quatre chemins" },
   { name: "Être à l'aise" },
   { name: "Être en train de cuver" },
   { name: "Être dans une impasse" },
   { name: "Être en train de se noyer" },
   { name: "Passer un savon" },
   { name: "Péter les plombs" },
   { name: "Prendre le taureau par les cornes" },
   { name: "Qui sème le vent récolte la tempête" },
   { name: "Rire jaune" },
   { name: "Rouler dans la farine" },
   { name: "Sauter du coq à l'âne" },
   { name: "Se creuser la tête" },
   { name: "Se mettre sur son 31" },
   { name: "Se prendre une veste" },
   { name: "Tirer les vers du nez" },
   { name: "Tomber dans les pommes" },
   { name: "Tomber de sommeil" },
   { name: "Tomber sur un os" },
   { name: "Tourner autour du pot" },
   { name: "Trouver chaussure à son pied" },
   { name: "Trouver la perle rare" },
   { name: "Un coup de pouce" },
   { name: "Un fauteuil roulant" },
   { name: "Un jeu d'enfant" },
   { name: "Un secret de polichinelle" },
   { name: "Une goutte d'eau dans l'océan" },
   { name: "Une main de fer dans un gant de velours" },
   { name: "Une peau de vache" },
   { name: "Une tempête dans un verre d'eau" },
   { name: "Vendre la peau de l'ours avant de l'avoir tué" },
   { name: "Être au bout du rouleau" },
   { name: "Être dans la lune" },
   { name: "Être dans le pétrin" },
   { name: "Être en train de mijoter quelque chose" },
   { name: "Être une poule mouillée" },
   { name: "Être une tête de mule" },
   { name: "Faire cavalier seul" },
   { name: "Faire d'une pierre deux coups" },
   { name: "Faire la grasse matinée" },
   { name: "Faire le pont" },
   { name: "Faire passer un message" },
   { name: "Mettre de l'eau dans son vin" },
   { name: "Mettre les pieds dans le plat" },
   { name: "Prendre son courage à deux mains" },
   { name: "Tirer son chapeau" }
])







   
	

	
	

	

