
-- NEW API --

db.themes.insertOne({
   theme: "expressions",
   label: "Expressions",
   element: ["Avoir un chat dans la gorge",
"Avoir les yeux plus gros que le ventre",
"Avoir un coup de foudre",
"À bon entendeur salut",
"Appuyer sur le champignon",
"Avoir la tête dans les nuages",
"Avoir le cœur sur la main",
"Avoir un cœur d'artichaut",
"C'est du gâteau",
"C'est la fin des haricots",
"C'est la goutte d'eau qui fait déborder le vase",
"C'est la vie",
"Chercher une aiguille dans une botte de foin",
"Coûter les yeux de la tête",
"De fil en aiguille",
"Donner sa langue au chat",
"Être à l'ouest",
"Être dans les nuages",
"Être dans la lune",
"Être aux abonnés absents",
"Faire des pieds et des mains",
"Faire la tête",
"Faire sa valise",
"Il ne faut pas mettre tous ses œufs dans le même panier",
"Être sur un petit nuage",
"Jouer avec le feu",
"Lâcher la grappe",
"Manger sur le pouce",
"Mettre de l'eau dans son vin",
"Mettre les pieds dans le plat",
"Mettre la main à la pâte",
"Ne pas avoir sa langue dans sa poche",
"Ne pas y aller par quatre chemins",
"Être à l'aise",
"Être en train de cuver",
"Être dans une impasse",
"Être en train de se noyer",
"Passer un savon",
"Péter les plombs",
"Prendre le taureau par les cornes",
"Qui sème le vent récolte la tempête",
"Rire jaune",
"Rouler dans la farine",
"Sauter du coq à l'âne",
"Se creuser la tête",
"Se mettre sur son 31",
"Se prendre une veste",
"Tirer les vers du nez",
"Tomber dans les pommes",
"Tomber de sommeil",
"Tomber sur un os",
"Tourner autour du pot",
"Trouver chaussure à son pied",
"Trouver la perle rare",
"Un coup de pouce",
"Un fauteuil roulant",
"Un jeu d'enfant",
"Un secret de polichinelle",
"Une goutte d'eau dans l'océan",
"Une main de fer dans un gant de velours",
"Une peau de vache",
"Une tempête dans un verre d'eau",
"Vendre la peau de l'ours avant de l'avoir tué",
"Être au bout du rouleau",
"Être dans la lune",
"Être dans le pétrin",
"Être en train de mijoter quelque chose",
"Être une poule mouillée",
"Être une tête de mule",
"Faire cavalier seul",
"Faire d'une pierre deux coups",
"Faire la grasse matinée" ,
"Faire le pont" ,
"Faire passer un message" ,
"Mettre de l'eau dans son vin" ,
"Mettre les pieds dans le plat" ,
"Prendre son courage à deux mains" ,
"Tirer son chapeau" ]
})

db.themes.insertOne({
   theme: "brands",
   label: "Marques",
   element: ["Air France",
"Peugeot",
"Renault",
"Michelin",
"Carrefour",
"Total",
"Danone",
"L'Oréal",
"Chanel",
"Hermès",
"Louis Vuitton",
"Cartier",
"Yves Saint Laurent",
"Dior",
"Givenchy",
"Guerlain",
"Clarins",
"Airbus",
"Orange",
"Bouygues Telecom",
"SFR",
"Free",
"EDF",
"Engie",
"Veolia",
"Suez",
"Vinci",
"Sanofi",
"LVMH",
"AccorHotels",
"Club Med",
"RATP",
"SNCF",
"Air Liquide",
"Safran",
"Thales",
"Alstom",
"Schneider Electric",
"Siemens",
"Orange",
"Canal+",
"Le Figaro",
"Le Monde",
"Les Echos",
"BNP Paribas",
"Société Générale",
"Crédit Agricole",
"La Poste",
"La Redoute",
"Fnac",
"Decathlon",
"Leroy Merlin",
"Castorama",
"Ikea",
"Carrefour",
"Auchan",
"Intermarché",
"Monoprix",
"Leclerc",
"Peugeot",
"Renault",
"Michelin",
"Citroën",
"Airbus",
"Air France",
"SNCF",
"Apple",
"Nike",
"Coca-Cola",
"Google",
"McDonald's",
"Amazon",
"Samsung",
"Toyota",
"BMW",
"Mercedes-Benz",
"Audi",
"Ford",
"Chevrolet",
"Pepsi",
"Adidas",
"Microsoft",
"Procter & Gamble",
"Unilever",
"Nestlé" ]
})

db.themes.insertOne({
   theme: "histories",
   label: "Evénements historiques",
   element: ["Jésus-Christ",
"Bouddha",
"Alexandre le Grand",
"Jules César",
"Cléopâtre",
"Napoléon Bonaparte",
"Genghis Khan",
"George Washington",
"Abraham Lincoln",
"Albert Einstein",
"Martin Luther King Jr.",
"Mahatma Gandhi",
"Winston Churchill",
"Franklin D. Roosevelt",
"John F. Kennedy",
"Nelson Mandela",
"Galilée",
"Isaac Newton",
"Charles Darwin",
"Marie Curie",
"Michel-Ange",
"Léonard de Vinci",
"Vincent van Gogh",
"Pablo Picasso",
"William Shakespeare",
"Edgar Allan Poe",
"Johann Sebastian Bach",
"Wolfgang Amadeus Mozart",
"Ludwig van Beethoven",
"Frédéric Chopin",
"Charles Babbage",
"Thomas Edison",
"Alexander Graham Bell",
"Henry Ford",
"Steve Jobs",
"Mark Zuckerberg",
"Mahomet",
"Confucius",
"Socrate",
"Aristote",
"La Guerre de Troie",
"La Révolution française",
"La chute de l'Empire romain",
"La découverte de l'Amérique",
"La Première Guerre mondiale",
"La découverte de l'électricité",
"Discours de Martin Luther King Jr. ('I Have a Dream', 1963)",
"La construction de la Grande Muraille de Chine",
"La Renaissance",
"La Guerre froide",
"La découverte de la gravitation universelle",
"La Révolution industrielle",
"La Guerre des étoiles",
"La chute du mur de Berlin",
"La découverte de l'ADN",
"La Guerre des Six Jours",
"La construction de la Tour Eiffel",
"La Guerre de Cent Ans",
"L'assassinat de Jules César",
"La conquête de l'Espagne par les Arabes",
"La découverte de l'Amérique du Sud" ]
})

db.themes.insertOne({
   theme: "sports",
   label: "Sports",
   element: ["Athlétisme",
"Aviron",
"Badminton",
"Baseball",
"Basket-ball",
"Beach-volley",
"Billard",
"Biathlon",
"Boxe",
"Canoë-kayak",
"Cricket",
"Curling",
"Cyclisme",
"Danse sportive",
"Équitation",
"Escalade",
"Escrime",
"Football",
"Football américain",
"Golf",
"Gymnastique artistique",
"Gymnastique rythmique",
"Haltérophilie",
"Handball",
"Hockey sur gazon",
"Hockey sur glace",
"Judo",
"Karaté",
"Kitesurf",
"Luge",
"Motocross",
"Natation",
"Patinage artistique",
"Patinage de vitesse",
"Pêche sportive",
"Pentathlon moderne",
"Pétanque",
"Planche à voile",
"Plongée sous-marine",
"Rafting",
"Randonnée pédestre",
"Roller derby",
"Rugby",
"Ski alpin",
"Ski de fond",
"Snowboard",
"Squash",
"Surf",
"Taekwondo",
"Tennis",
"Tennis de table",
"Tir à l'arc",
"Tir sportif",
"Triathlon",
"Ultimate Frisbee",
"Varappe",
"Voile",
"Volley-ball",
"Water-polo",
"Yoga",
"Marche nordique",
"Course d'orientation",
"Course de chevaux",
"Polo",
"Course de dragsters",
"Course automobile",
"Course de drones",
"Course de motos",
"Course de bateaux",
"Aérobic",
"Alpinisme",
"Barre au sol",
"Cross-country",
"Danse contemporaine",
"Hapkido",
"Jiu-jitsu",
"Karaté Kyokushinkai",
"Kung-fu",
"Taï-chi-chuan" ]
})

db.themes.insertOne({
   theme: "athletes",
   label: "Athlètes",
   element: ["Muhammad Ali",
"Michael Jordan",
"Pelé",
"Usain Bolt",
"Lionel Messi",
"Cristiano Ronaldo",
"Diego Maradona",
"Roger Federer",
"Serena Williams",
"Rafael Nadal",
"Tiger Woods",
"Mike Tyson",
"Floyd Mayweather Jr.",
"Kobe Bryant",
"Michael Phelps",
"Carl Lewis",
"Jesse Owens",
"Wayne Gretzky",
"David Beckham",
"Zinedine Zidane",
"Ronaldinho",
"Neymar",
"Lebron James",
"Shaquille O'Neal",
"Magic Johnson",
"Larry Bird",
"Manny Pacquiao",
"Sugar Ray Leonard",
"Georges St-Pierre",
"Royce Gracie",
"Jon Jones",
"Conor McGregor",
"Georges Laraque",
"Michael Schumacher",
"Ayrton Senna",
"Lewis Hamilton",
"Valentino Rossi",
"Eddy Merckx",
"Lance Armstrong",
"Martina Navratilova",
"Steffi Graf",
"Novak Djokovic",
"Pete Sampras",
"Andre Agassi",
"Roger Clemens",
"Barry Bonds",
"Michael Vick",
"Jerry Rice",
"Tom Brady",
"Joe Montana",
"Serena Williams",
"Martina Hingis",
"Ronda Rousey",
"Holly Holm",
"Simone Biles",
"Nadia Comaneci",
"Bonnie Blair",
"Eric Heiden",
"Wayne Gretzky",
"Bobby Orr",
"Mario Lemieux",
"Sidney Crosby",
"Michael Owen",
"Johan Cruyff",
"Franz Beckenbauer",
"Lev Yashin",
"Zlatan Ibrahimovic",
"Usain Bolt",
"Carl Lewis",
"Edwin Moses",
"Jackie Joyner-Kersee",
"Greg Louganis",
"Teddy Riner",
"Marcel Cerdan",
"Khabib Nurmagomedov",
"Francis N'Gannou",
"Kyrie Irving",
"Vince Carter" ]
})

db.themes.insertOne({
   theme: "movies",
   label: "Films cultes",
   element: ["Bienvenue chez les Ch'tis",
"Intouchables",
"Les Visiteurs",
"La French",
"Les Tuches",
"Qu'est-ce qu'on a fait au Bon Dieu ?",
"Les Bronzés",
"La Grande Vadrouille",
"Astérix et Obélix Mission Cléopatre",
"La Vérité si je mens !",
"Les Bronzés font du ski",
"RRRrrrr!!!",
"L'Arnacœur",
"Taxi",
"OSS 117",
"Le Prénom",
"Le Dîner de Cons",
"Les Infidèles",
"Les Choristes",
"Le Petit Nicolas",
"Le Fabuleux Destin d'Amélie Poulain",
"Le Pacte des loups",
"Le Père Noël est une ordure",
"Les Rivières pourpres",
"Camping",
"Nikita",
"Un Indien dans la ville",
"Pattaya",
"La Cage aux Folles",
"Avatar",
"Titanic",
"Star Wars",
"Jurassic World",
"Frozen",
"Harry Potter et les Reliques de la Mort",
"The Dark Knight : Le Chevalier noir",
"Fast and Furious",
"Le Hobbit",
"Iron Man",
"Le Seigneur des Anneaux",
"Jumanji",
"Les Minions",
"Finding Dory",
"Spectre",
"Skyfall",
"Pirates des Caraïbes",
"Le Retour de Mary Poppins",
"La Belle et la Bête",
"La Reine des neiges",
"Transformers",
"Les Animaux fantastiques",
"Transformers : La Revanche",
"Mission: Impossible",
"Les Avengers",
"Spider-Man",
"Forrest Gump",
"Le Silence des Agneaux",
"Birdman",
"Million Dollar Baby",
"Rocky",
"Le parrain",
"Gladiator",
"Le Discours d'un Roi",
"Rain Man",
"Argo",
"Le Patient Anglais",
"American Beauty",
"Braveheart",
"La Liste de Schindler",
"Les Évadés",
"No Country for Old Men",
"Grease",
"Pretty Woman",
"Le diable s'habille en Prada",
"Black Panther",
"Joker",
"La ligne verte",
"12 hommes en colère",
"Vol au dessus d'un nid de coucou" ]
})

db.themes.insertOne({
   theme: "jobs",
   label: "Métiers",
   element: ["Comptable",
"Acupuncteur",
"Architecte",
"Détective privé",
"Artiste",
"Designer de jeux vidéo",
"Boulanger",
"Critique de cinéma",
"Banquier",
"Chercheur de fantômes",
"Barman",
"Expert en éthique de l'IA",
"Conducteur de bus",
"Parolier",
"Chef cuisinier",
"Testeur de nourriture pour animaux de compagnie",
"Ingénieur civil",
"Biographe",
"Agent de nettoyage",
"Spécialiste en communication non verbale",
"Programmeur informatique",
"Évaluateur de bijoux",
"Représentant du service client",
"Astrologue",
"Dentiste",
"Dresseur de chiens",
"Docteur",
"Thérapeute en art",
"Électricien",
"Géomètre",
"Ingénieur",
"Créateur de mode pour animaux de compagnie",
"Agriculteur",
"Spécialiste en énergie renouvelable",
"Styliste",
"Éducateur canin",
"Pompier",
"Expert en éclairage de scène",
"Entraîneur de fitness",
"Contrôleur de la qualité de l'air",
"Agent de bord",
"Art-thérapeute",
"Coiffeur",
"Éthologue",
"Gérant d'hôtel",
"Conservateur de musée",
"Responsable des ressources humaines",
"Parfumeur",
"Journaliste",
"Ethnographe",
"Avocat",
"Chirurgien esthétique",
"Bibliothécaire",
"Analyste du comportement",
"Enseignant",
"Analyste de la criminalité",
"Chercheur en cryptographie",
"Technicien en maintenance",
"Historien de l'art",
"Directeur marketing",
"Massothérapeute",
"Ingénieur mécanique",
"Optométriste",
"Plombier",
"Psychologue",
"Agent immobilier",
"Mécanicien automobile",
"Enseignant d'école primaire",
"Enseignant d'université",
"Écrivain" ]
})

db.themes.insertOne({
   theme: "singers",
   label: "Chanteurs / Chanteuses",
   element: ["Edith Piaf",
"The Beatles",
"Jacques Brel",
"Michael Jackson",
"Serge Gainsbourg",
"Madonna",
"Charles Aznavour",
"Whitney Houston",
"Johnny Hallyday",
"Prince",
"Dalida",
"Elton John",
"Francis Cabrel",
"Freddie Mercury/Queen",
"Jean-Jacques Goldman",
"David Bowie",
"Mylène Farmer",
"Stevie Wonder",
"Vanessa Paradis",
"Bruce Springsteen",
"Zazie",
"Bob Dylan",
"Alain Bashung",
"Fleetwood Mac",
"Patricia Kaas",
"The Rolling Stones",
"Carla Bruni",
"Pink Floyd",
"Mireille Mathieu",
"Led Zeppelin",
"Renaud",
"Nirvana",
"Christophe Maé",
"Pearl Jam",
"Patrick Bruel",
"U2",
"Kyo",
"Metallica",
"Indochine",
"Guns N' Roses",
"Téléphone",
"AC/DC",
"Noir Désir",
"Aerosmith",
"Superbus",
"Bon Jovi",
"Céline Dion",
"Madonna",
"Stromae",
"Mariah Carey",
"Johnny Clegg",
"Beyoncé",
"Angèle",
"Lady Gaga",
"La Grande Sophie",
"Taylor Swift",
"Christophe Willem",
"Rihanna",
"Calogero",
"Adele",
"Véronique Sanson",
"Justin Timberlake",
"Michel Sardou",
"Bruno Mars",
"Benjamin Biolay",
"Ed Sheeran",
"Julien Doré",
"Justin Bieber",
"Francis Lalanne",
"The Red Hot Chili Peppers",
"Nolwenn Leroy",
"Oasis"]
})

db.themes.insertOne({
   theme: "actors",
   label: "Acteurs",
   element: [
"Jean Reno",
"Tom Hanks",
"Anthony Hopkins",
"Marion Cotillard",
"Meryl Streep",
"Daniel Craig",
"Vincent Cassel",
"Brad Pitt",
"Kate Winslet",
"Audrey Tautou",
"Leonardo DiCaprio",
"Benedict Cumberbatch",
"Gérard Depardieu",
"Jennifer Lawrence",
"Helen Mirren",
"Sophie Marceau",
"Denzel Washington",
"Colin Firth",
"Omar Sy",
"Robert De Niro",
"Emma Watson",
"Juliette Binoche",
"Al Pacino",
"Jude Law",
"Isabelle Huppert",
"Angelina Jolie",
"Tom Hardy",
"Jean Dujardin",
"George Clooney",
"Keira Knightley",
"Léa Seydoux",
"Sandra Bullock",
"Idris Elba",
"François Cluzet",
"Johnny Depp",
"Michael Caine",
"Catherine Deneuve",
"Julia Roberts",
"Maggie Smith",
"Romain Duris",
"Scarlett Johansson",
"Emily Blunt",
"Nathalie Baye",
"Will Smith",
"Hugh Grant",
"Vincent Lindon",
"Emma Stone",
"Emma Thompson",
"Emmanuelle Béart",
"Ryan Gosling",
"Sean Connery",
"Alain Delon",
"Christian Bale",
"Ian McKellen",
"Bérénice Bejo",
"Tom Cruise",
"Judi Dench",
"Louis de Funès",
"Clint Eastwood",
"David Tennant",
"Omar Sharif",
"Mark Wahlberg",
"Carey Mulligan",
"Mathieu Kassovitz",
"Harrison Ford",
"Timothy Spall",
"Daniel Auteuil",
"Morgan Freeman",
"Ralph Fiennes",
"Guillaume Canet",
"Samuel L. Jackson",
"Eddie Redmayne",
"Viola Davis",
"Tom Hiddleston",
"Matthew McConaughey",
"Benedict Wong",
"Anne Hathaway",
"Andrew Scott",
"Daniel Day-Lewis",
"Chiwetel Ejiofor",
"Cate Blanchett",
"John Boyega",
"Heath Ledger",
"Helena Bonham Carter",
"Robert Downey Jr.",
"Tilda Swinton",
"Robin Williams",
"Naomi Watts",
"Dustin Hoffman",
"Iain Glen",
"Keanu Reeves",
"Colin Farrell",
"Timothée Chalamet",
"Emily Mortimer",
"Lupita Nyong'o",
"Dev Patel"
      ]
})

db.themes.insertOne({
   theme: "disneys",
   label: "Disney",
   element: [
"Mickey Mouse",
"Timon and Pumbaa",
"Minnie Mouse",
"Sebastian",
"Donald Duck",
"Lumiere",
"Goofy",
"Cogsworth",
"Woody",
"Genie",
"Mushu",
"Nemo",
"Jiminy Cricket",
"Dory",
"Jaq and Gus",
"Simba",
"Olaf",
"Belle",
"Sven",
"Ariel",
"Kristoff",
"Cinderella",
"Hiro Hamada",
"Elsa",
"Baymax",
"Anna",
"Mater",
"Rapunzel",
"Lightning McQueen",
"Peter Pan",
"WALL-E",
"Tinker Bell",
"Eve",
"Winnie the Pooh",
"Merida",
"Tiana",
"Lilo",
"Aladdin",
"Jumba Jookiba",
"Pocahontas",
"Maui",
"Mulan",
"Heihei",
"Hercules",
"Pinocchio",
"Stitch",
"Moana",
"Black Widow",
"Iron Man",
"Captain America",
"Spider-Man",
"Shuri",
"Bucky Barnes",
"Peggy Carter",
"Hawkeye",
"Ant-Man",
"The Wasp",
"Yondu",
"Ursula",
"Jafar",
"Scar",
"Flounder",
"Remy",
"Disgust"
]
})

db.themes.insertOne({
   theme: "animals",
   label: "Animaux",
   element: [
"Lion",
"Tigre",
"Éléphant",
"Girafe",
"Zèbre",
"Ours polaire",
"Panda",
"Léopard",
"Guépard",
"Jaguar",
"Loup",
"Renard",
"Coyote",
"Hyène",
"Chat",
"Chien",
"Lapin",
"Koala",
"Kangourou",
"Wombat",
"Ours brun",
"Grizzly",
"Puma",
"Lynx",
"Caribou",
"Cerf",
"Antilope",
"Chameau",
"Dromadaire",
"Gorille",
"Chimpanzé",
"Orang-outan",
"Babouin",
"Singe araignée",
"Mandrill",
"Perroquet",
"Toucan",
"Colibri",
"Flamant rose",
"Pingouin",
"Baleine",
"Dauphin",
"Requin",
"Poulpe",
"Calmar géant",
"Crocodile",
"Alligator",
"Serpent",
"Cobra",
"Python",
"Scorpion",
"Araignée",
"Fourmi",
"Abeille",
"Papillon",
"Libellule",
"Escargot",
"Crabe",
"Étoile de mer",
"Méduse",
"Crapaud",
"Grenouille",
"Salamandre",
"Iguane",
"Gecko",
"Caméléon",
"Tortue",
"Crevette",
"Homard",
"Écrevisse",
"Pieuvre",
"Coquille Saint-Jacques",
"Mouette",
"Corbeau",
"Aigle",
"Faucon",
"Hibou",
"Colombe",
"Pigeon",
"Rhinocéros"
]
})




   
	

	
	

	

